/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as FormatosRouteImport } from './routes/formatos'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as NcfRouteImport } from './routes/ncf'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ConducesIndexRouteImport } from './routes/conduces.index'
import { Route as ConducesIdRouteImport } from './routes/conduces.$id'
import { Route as ConducesNuevaRouteImport } from './routes/conduces.nueva'
import { Route as CotizacionesIndexRouteImport } from './routes/cotizaciones.index'
import { Route as CotizacionesIdRouteImport } from './routes/cotizaciones.$id'
import { Route as CotizacionesNuevaRouteImport } from './routes/cotizaciones.nueva'
import { Route as DevolucionesIndexRouteImport } from './routes/devoluciones.index'
import { Route as FacturasIndexRouteImport } from './routes/facturas.index'
import { Route as FacturasIdRouteImport } from './routes/facturas.$id'
import { Route as FacturasNuevaRouteImport } from './routes/facturas.nueva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatosRoute = FormatosRouteImport.update({
  id: '/formatos',
  path: '/formatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const NcfRoute = NcfRouteImport.update({
  id: '/ncf',
  path: '/ncf',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConducesIndexRoute = ConducesIndexRouteImport.update({
  id: '/conduces/',
  path: '/conduces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConducesIdRoute = ConducesIdRouteImport.update({
  id: '/conduces/$id',
  path: '/conduces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConducesNuevaRoute = ConducesNuevaRouteImport.update({
  id: '/conduces/nueva',
  path: '/conduces/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesIndexRoute = CotizacionesIndexRouteImport.update({
  id: '/cotizaciones/',
  path: '/cotizaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesIdRoute = CotizacionesIdRouteImport.update({
  id: '/cotizaciones/$id',
  path: '/cotizaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesNuevaRoute = CotizacionesNuevaRouteImport.update({
  id: '/cotizaciones/nueva',
  path: '/cotizaciones/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucionesIndexRoute = DevolucionesIndexRouteImport.update({
  id: '/devoluciones/',
  path: '/devoluciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasIndexRoute = FacturasIndexRouteImport.update({
  id: '/facturas/',
  path: '/facturas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasIdRoute = FacturasIdRouteImport.update({
  id: '/facturas/$id',
  path: '/facturas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasNuevaRoute = FacturasNuevaRouteImport.update({
  id: '/facturas/nueva',
  path: '/facturas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/formatos': typeof FormatosRoute
  '/items': typeof ItemsRoute
  '/ncf': typeof NcfRoute
  '/reportes': typeof ReportesRoute
  '/conduces/$id': typeof ConducesIdRoute
  '/conduces/nueva': typeof ConducesNuevaRoute
  '/cotizaciones/$id': typeof CotizacionesIdRoute
  '/cotizaciones/nueva': typeof CotizacionesNuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas/nueva': typeof FacturasNuevaRoute
  '/conduces/': typeof ConducesIndexRoute
  '/cotizaciones/': typeof CotizacionesIndexRoute
  '/devoluciones/': typeof DevolucionesIndexRoute
  '/facturas/': typeof FacturasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/formatos': typeof FormatosRoute
  '/items': typeof ItemsRoute
  '/ncf': typeof NcfRoute
  '/reportes': typeof ReportesRoute
  '/conduces/$id': typeof ConducesIdRoute
  '/conduces/nueva': typeof ConducesNuevaRoute
  '/cotizaciones/$id': typeof CotizacionesIdRoute
  '/cotizaciones/nueva': typeof CotizacionesNuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas/nueva': typeof FacturasNuevaRoute
  '/conduces': typeof ConducesIndexRoute
  '/cotizaciones': typeof CotizacionesIndexRoute
  '/devoluciones': typeof DevolucionesIndexRoute
  '/facturas': typeof FacturasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/formatos': typeof FormatosRoute
  '/items': typeof ItemsRoute
  '/ncf': typeof NcfRoute
  '/reportes': typeof ReportesRoute
  '/conduces/$id': typeof ConducesIdRoute
  '/conduces/nueva': typeof ConducesNuevaRoute
  '/cotizaciones/$id': typeof CotizacionesIdRoute
  '/cotizaciones/nueva': typeof CotizacionesNuevaRoute
  '/facturas/$id': typeof FacturasIdRoute
  '/facturas/nueva': typeof FacturasNuevaRoute
  '/conduces/': typeof ConducesIndexRoute
  '/cotizaciones/': typeof CotizacionesIndexRoute
  '/devoluciones/': typeof DevolucionesIndexRoute
  '/facturas/': typeof FacturasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/formatos'
    | '/items'
    | '/ncf'
    | '/reportes'
    | '/conduces/$id'
    | '/conduces/nueva'
    | '/cotizaciones/$id'
    | '/cotizaciones/nueva'
    | '/facturas/$id'
    | '/facturas/nueva'
    | '/conduces/'
    | '/cotizaciones/'
    | '/devoluciones/'
    | '/facturas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/formatos'
    | '/items'
    | '/ncf'
    | '/reportes'
    | '/conduces/$id'
    | '/conduces/nueva'
    | '/cotizaciones/$id'
    | '/cotizaciones/nueva'
    | '/facturas/$id'
    | '/facturas/nueva'
    | '/conduces'
    | '/cotizaciones'
    | '/devoluciones'
    | '/facturas'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/formatos'
    | '/items'
    | '/ncf'
    | '/reportes'
    | '/conduces/$id'
    | '/conduces/nueva'
    | '/cotizaciones/$id'
    | '/cotizaciones/nueva'
    | '/facturas/$id'
    | '/facturas/nueva'
    | '/conduces/'
    | '/cotizaciones/'
    | '/devoluciones/'
    | '/facturas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  FormatosRoute: typeof FormatosRoute
  ItemsRoute: typeof ItemsRoute
  NcfRoute: typeof NcfRoute
  ReportesRoute: typeof ReportesRoute
  ConducesIdRoute: typeof ConducesIdRoute
  ConducesNuevaRoute: typeof ConducesNuevaRoute
  CotizacionesIdRoute: typeof CotizacionesIdRoute
  CotizacionesNuevaRoute: typeof CotizacionesNuevaRoute
  FacturasIdRoute: typeof FacturasIdRoute
  FacturasNuevaRoute: typeof FacturasNuevaRoute
  ConducesIndexRoute: typeof ConducesIndexRoute
  CotizacionesIndexRoute: typeof CotizacionesIndexRoute
  DevolucionesIndexRoute: typeof DevolucionesIndexRoute
  FacturasIndexRoute: typeof FacturasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formatos': {
      id: '/formatos'
      path: '/formatos'
      fullPath: '/formatos'
      preLoaderRoute: typeof FormatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncf': {
      id: '/ncf'
      path: '/ncf'
      fullPath: '/ncf'
      preLoaderRoute: typeof NcfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conduces/': {
      id: '/conduces/'
      path: '/conduces'
      fullPath: '/conduces/'
      preLoaderRoute: typeof ConducesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conduces/$id': {
      id: '/conduces/$id'
      path: '/conduces/$id'
      fullPath: '/conduces/$id'
      preLoaderRoute: typeof ConducesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conduces/nueva': {
      id: '/conduces/nueva'
      path: '/conduces/nueva'
      fullPath: '/conduces/nueva'
      preLoaderRoute: typeof ConducesNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones/': {
      id: '/cotizaciones/'
      path: '/cotizaciones'
      fullPath: '/cotizaciones/'
      preLoaderRoute: typeof CotizacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones/$id': {
      id: '/cotizaciones/$id'
      path: '/cotizaciones/$id'
      fullPath: '/cotizaciones/$id'
      preLoaderRoute: typeof CotizacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones/nueva': {
      id: '/cotizaciones/nueva'
      path: '/cotizaciones/nueva'
      fullPath: '/cotizaciones/nueva'
      preLoaderRoute: typeof CotizacionesNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devoluciones/': {
      id: '/devoluciones/'
      path: '/devoluciones'
      fullPath: '/devoluciones/'
      preLoaderRoute: typeof DevolucionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas/': {
      id: '/facturas/'
      path: '/facturas'
      fullPath: '/facturas/'
      preLoaderRoute: typeof FacturasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas/$id': {
      id: '/facturas/$id'
      path: '/facturas/$id'
      fullPath: '/facturas/$id'
      preLoaderRoute: typeof FacturasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas/nueva': {
      id: '/facturas/nueva'
      path: '/facturas/nueva'
      fullPath: '/facturas/nueva'
      preLoaderRoute: typeof FacturasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  FormatosRoute: FormatosRoute,
  ItemsRoute: ItemsRoute,
  NcfRoute: NcfRoute,
  ReportesRoute: ReportesRoute,
  ConducesIdRoute: ConducesIdRoute,
  ConducesNuevaRoute: ConducesNuevaRoute,
  CotizacionesIdRoute: CotizacionesIdRoute,
  CotizacionesNuevaRoute: CotizacionesNuevaRoute,
  FacturasIdRoute: FacturasIdRoute,
  FacturasNuevaRoute: FacturasNuevaRoute,
  ConducesIndexRoute: ConducesIndexRoute,
  CotizacionesIndexRoute: CotizacionesIndexRoute,
  DevolucionesIndexRoute: DevolucionesIndexRoute,
  FacturasIndexRoute: FacturasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
