/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as NcfRouteImport } from './routes/ncf'
import { Route as FacturasIndexRouteImport } from './routes/facturas.index'
import { Route as FacturasNuevaRouteImport } from './routes/facturas.nueva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const NcfRoute = NcfRouteImport.update({
  id: '/ncf',
  path: '/ncf',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasIndexRoute = FacturasIndexRouteImport.update({
  id: '/facturas/',
  path: '/facturas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasNuevaRoute = FacturasNuevaRouteImport.update({
  id: '/facturas/nueva',
  path: '/facturas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/items': typeof ItemsRoute
  '/ncf': typeof NcfRoute
  '/facturas/nueva': typeof FacturasNuevaRoute
  '/facturas/': typeof FacturasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/items': typeof ItemsRoute
  '/ncf': typeof NcfRoute
  '/facturas/nueva': typeof FacturasNuevaRoute
  '/facturas': typeof FacturasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/items': typeof ItemsRoute
  '/ncf': typeof NcfRoute
  '/facturas/nueva': typeof FacturasNuevaRoute
  '/facturas/': typeof FacturasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/clientes' | '/items' | '/ncf' | '/facturas/nueva' | '/facturas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes' | '/items' | '/ncf' | '/facturas/nueva' | '/facturas'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/items'
    | '/ncf'
    | '/facturas/nueva'
    | '/facturas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ItemsRoute: typeof ItemsRoute
  NcfRoute: typeof NcfRoute
  FacturasNuevaRoute: typeof FacturasNuevaRoute
  FacturasIndexRoute: typeof FacturasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncf': {
      id: '/ncf'
      path: '/ncf'
      fullPath: '/ncf'
      preLoaderRoute: typeof NcfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas/': {
      id: '/facturas/'
      path: '/facturas'
      fullPath: '/facturas/'
      preLoaderRoute: typeof FacturasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas/nueva': {
      id: '/facturas/nueva'
      path: '/facturas/nueva'
      fullPath: '/facturas/nueva'
      preLoaderRoute: typeof FacturasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ItemsRoute: ItemsRoute,
  NcfRoute: NcfRoute,
  FacturasNuevaRoute: FacturasNuevaRoute,
  FacturasIndexRoute: FacturasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
